### ISSUE TITLE
API Requests giving me a 401 since 20.02.2019  1pm

### ISSUE THREAD

**Issue by HolgerHees** [MeteoGroup/weather-api#15]
Hello,

I'm using your great weather api since 3 years now inside my private home automation project. Details can be found here.

http://www.intranet-of-things.com/smarthome/house/heating/control/

But since 20.02.2019 1pm it does not work anymore. I'm getting always a 401 to every request. I'm still using the same credentials I got 3 years ago.

I already tried the contact form related to the weather api 2 days ago, but without any reaction. I also tried the main contact form on your web site. Also without any reaction. I tried also your MeteoGroup Help Center. There I got the answer I should use the contact form.

So this is my desperate try to get any information, what is wrong. I really spend a lot of work in all my automation script depending on your data. I hope you have not closed it for me. Because I was a helpful beta tester for years now. An it would be surprising, because there was no announcement before to give me the chance to prepare.

but maybe this is just a bug. From my perspective, hopefully it is a bug or wrong configuration. :-)

best

Holger

**Comment by HolgerHees** [comment]
Hi, is this project is dead? No one is answering here. Also any try to use official contact forms is not successful. I tried the website contact form, I tried the contact form mentioned on the API website.

zero reaction. I mean, I'm a private user who provided good beta tester feedback to you, so I don't expect business support. But at least an email answer to let the people know that someone is reading the email.

also as a private user I depend on this project because in the past you was offering it to the public and I was building all my private programs on the top of this API.

Now, at some point I have to decide for my self if it makes sense to wait some more days or if I should port all my programs to a different weather API service. But I want to avoid this, because I liked your service in the past.

**Comment by CoenVerrijnStuart** [comment]
Dear Holger,
Thanks for contacting us. It seems you are using a legacy key authentication method that unexpectedly crashed during an update last week. I will reach out to you separately for creating a new key. Please contact our customerservice@meteogroup.com and I will make sure it is arranged.

**Comment by HolgerHees** [comment]
thanks a lot for your answer? I will write a message to the customer service.
