### ISSUE TITLE
401

### ISSUE THREAD

**Issue by KobetiakMykola** [MeteoGroup/weather-api#27]
Hi, have some problem when i use Api
{
    "status": 401,
    "message": "Unauthorized"
}
where i must signup?

**Comment by adfer** [comment]
Hi @KobetiakMykola. Thank you for reaching us out.
Please follow this instruction to request contact from MeteoGroup's company: https://api.weather.mg/#access

**Comment by KobetiakMykola** [comment]
> Hi @KobetiakMykola. Thank you for reaching us out.
> Please follow this instruction to request contact from MeteoGroup's company: https://api.weather.mg/#access

thanks
